### PR TITLE
bootstrap.sh: verify checksum of Eigen tar file

### LINKED ISSUE #196: Verify checksum of Eigen in bootstrap.sh
There should be at least some kind of validation before running code from an unvalidated source. The script bootstrap.sh downloads the file via
wget ${EIGEN_URL} --no-check-certificate && ./scripts/update_eigen.sh ${ARC} && rm ${ARC}
and explicitly disables any checks by the option --no-check-certificate.

Being careful not to break any existing setups, I propose to check the checksum if sha256sum or md5sum exists and to throw a warning otherwise. If the check is performed and the verification fails, the execution of bootstrap.sh should be aborted immediately.

### PR DESCRIPTION
**Pull request by nils-asmussen**
Fixes #196 , needs sha256sum

### CODE REVIEW

**Comment by nils-asmussen** [comment]
Travis CI: ./bootstrap.sh: line 11: sha256sum: command not found
Is it easy to install sha256sum in Travis CI?

**Comment by aportelli** [comment]
Hi Nils, I will look into it, but considering the amount of incoming code right now I have to warn you that this might not have the highest priority.

**Comment by paboyle** [comment]
I'm not sure I want to insist that anyone using Grid MUST have sha256sum ? Perhaps check if it exists?

**Comment by nils-asmussen** [comment]
It is okay for me to have the check depend on the availability of sha256sum, I have implemented it.

**Comment by aportelli** [comment]
Hi Nils, could you update from `develop` and check that the Eigen hash has not changed since their relocation to GitLab?

**Comment by nils-asmussen** [comment]
Hi Antonin, the most recent version of `develop` is merged now and I have updated the checksum. It has indeed changed.

**Comment by aportelli** [comment]
Thanks!

**Pull request merged**
