### PR TITLE
Added gauge transform option to eigpack IO

### PR DESCRIPTION
**Pull request by fionnoh**

### CODE REVIEW

**Comment by aportelli** [comment]
Hi Fionn,

Thank you very much. Two quick things:

- You should be able to get the GImpl from the FImpl, right? That would avoid overloading the template structure for the module.
- Please add a message when gauge fixing happen, and possibly a timer on it. The message is important so that we can cross-check In logs that it actually happened.

Best,

Antonin

**Comment by fionnoh** [comment]
Hi Antonin,

do we have FImpl? FImpl is in the template of Pack, but not the module itself.

Sure, I can add in timing and more logging.

Fionn

**Comment by aportelli** [comment]
You are right about the FImpl, we should keep it that way. Actually not depending on FImpl is something important for loading eigenvectors from non-fermionic operators (Laplacian).

The code looks ready thank! What tests/checks did you make?

**Comment by fionnoh** [comment]
I tested on a 16^3 configuration.

Undeflated CG **~900-1000 iterations**:

Hadrons : Message  : 769.116770 s : ---------------- Measurement step 13/14 (module 'uQZ2') ----------------
Hadrons : Message  : 769.116910 s : ................ Module execution
Hadrons : Message  : 769.340049 s : Computing quark propagator 'uQZ2'
Hadrons : Message  : 769.340079 s : Inverting using solver 'uCG_l' on source 'z2'
Hadrons : Message  : 769.340088 s : Inversion for spin= 0, color= 0
Hadrons : Message  : 769.340096 s : Import source
Hadrons : Message  : 769.475893 s : Solve
Grid    : Message  : 885.447479 s : ConjugateGradient Converged on iteration 959
Grid    : Message  : 885.447495 s : 	Computed residual 9.88905e-09
Grid    : Message  : 885.447522 s : 	True residual 9.88905e-09
Grid    : Message  : 885.447534 s : 	Target 1e-08



Regular deflated CG **~330 iterations**:
Hadrons : Message  : 21.703493 s : ---------------- Measurement step 6/14 (module 'QZ2') ----------------
Hadrons : Message  : 21.703506 s : ................ Module execution
Hadrons : Message  : 22.539570 s : Computing quark propagator 'QZ2'
Hadrons : Message  : 22.539960 s : Inverting using solver 'CG_l' on source 'z2'
Hadrons : Message  : 22.540040 s : Inversion for spin= 0, color= 0
Hadrons : Message  : 22.540140 s : Import source
Hadrons : Message  : 22.186428 s : Solve
Grid    : Message  : 60.842256 s : ConjugateGradient Converged on iteration 332
Grid    : Message  : 60.842272 s : 	Computed residual 9.7613e-09
Grid    : Message  : 60.842298 s : 	True residual 9.7613e-09
Grid    : Message  : 60.842310 s : 	Target 1e-08



Deflated CG for fixed gauge **~330 iterations**:
Hadrons : Message  : 305.389179 s : ---------------- Measurement step 8/10 (module 'fQZ2') ----------------
Hadrons : Message  : 305.389193 s : ................ Module execution
Hadrons : Message  : 305.717818 s : Computing quark propagator 'fQZ2'
Hadrons : Message  : 305.717860 s : Inverting using solver 'fCG_l' on source 'z2'
Hadrons : Message  : 305.717868 s : Inversion for spin= 0, color= 0
Hadrons : Message  : 305.717876 s : Import source
Hadrons : Message  : 305.858255 s : Solve
Grid    : Message  : 346.101627 s : ConjugateGradient Converged on iteration 331
Grid    : Message  : 346.101643 s : 	Computed residual 9.80137e-09
Grid    : Message  : 346.101671 s : 	True residual 9.80137e-09
Grid    : Message  : 346.101683 s : 	Target 1e-08

**Comment by fionnoh** [comment]
For a fixed gauge with parameters stolen from Julia:

<module>
      <id>
        <name>fgauge</name>
        <type>MGauge::GaugeFix</type>
      </id>
      <options>
        <gauge>gauge</gauge>
        <alpha>0.05</alpha>
        <maxiter>1000000</maxiter>
        <Omega_tol>1e-8</Omega_tol>
        <Phi_tol>1e-8</Phi_tol>
        <Fourier>true</Fourier>
      </options>
    </module>

**Comment by aportelli** [comment]
Brilliant, thank you very much.

**Pull request merged**
