### PR TITLE
Hotfix/bgq

### PR DESCRIPTION
**Pull request by Lanny91**
Added missing QPX functions, although no actual precision change functionality. I also added an integer reduce + test for QPX. Integer reductions were unimplemented for other SIMD types so I implemented them for most currently supported types.

### CODE REVIEW

**Comment by aportelli** [comment]
Hi Andrew, it sounds from the CI that your request does not build. You can investigate at https://ci.cliath.ph.ed.ac.uk (it will appear at `pull/118`). You can create an account there to receive notifications when this happens. Any update you push on your `hotfix/bgq` should trigger a rebuild here.

**Comment by Lanny91** [comment]
Fixed, all tests now passing.

**Comment by aportelli** [comment]
Thanks. I can see that you modified the x86 SIMD code, this is very sensitive code we need to be extra careful so I need to understand why this is necessary. My understanding is that you were correcting the QPX code to make it compatible with the latest changes, the x86 code was already functional and passing CI so why does it need to be modified?

**Comment by Lanny91** [comment]
The x86 code was missing `Reduce` functions for integer vectors (the functions were defined but with a "FIXME" comment, and fired an assert if used). I added these for QPX and additionally a test in Test_simd.cc, but then to assure Test_simd would pass universally I had to add the x86 versions.

**Comment by aportelli** [comment]
Ok thanks I looked in more details this looks good to me. Thanks for adding that. However because the x86 SIMD code is modified I would like to have Peter's blessing for merging. Hopefully he is seeing this discussion, otherwise we can try to catch him on Monday's call. In any case let's sort that out quickly to make progress with the BG/Q code.

**Comment by paboyle** [comment]
It looks like he is right to me. Amazed it got through testing and we need to make sure we cover the test escape. I need to take over the BG/Q responsibility from Andrew soon as this is rising to the top of my priorities. Could we have a summary of what test coverage Andrew has done on the BG/Q ?

**Comment by aportelli** [comment]
Ok thanks Peter I'll just merge then, I propose that we continue the important discussion on BG/Q testing in issue #106.

**Pull request merged**
