### PR TITLE
Proposal for Travis update + minor build system fix

### PR DESCRIPTION
**Pull request by aportelli**
#### Proposal for Travis update
- configured for container-based builds (it is not clear how long Travis will support the `sudo` based builds on Trusty)
- build matrix: linux (gcc 4.9 & 5, clang 3.6 & 3.7) and OS X (clang XCode 7.2 & gcc 5)
- configured builds for SSE 4.2 (it looks a bit random which ISA the VM supports, SSE looks old enough to be always supported)
- added Travis status (for paboyle/Grid, not my repository) to the README

It works (_e.g._ https://travis-ci.org/aportelli/Grid/builds/127065180). Let me know if you think something must be changed.

#### Small build fix
I figured out why the automake issue reappeared, it is because `scripts/filelist` was not corrected.

### CODE REVIEW

**Comment by paboyle** [comment]
Hi Antonin, 
I'm against downlevel clang compiles -- 3.8 was the first to include OMP on the main
branch and I think we should go for 3.8 and onwards since in some deep HPC sense clang
was broken prior to 3.8. Thoughts welcome. You are clearly more skilled with travis than I.
Peter

**Comment by paboyle** [comment]
Also -- I'm surprised -- please confirm travis can do MacOSX ???

**Comment by aportelli** [comment]
Hi Peter,
I agree with you for clang 3.8, I included older versions for the following reasons. The thing is that 3.8 is not very spread yet and we probably want people to be able to compile Grid on their laptop. OS X is really for laptop development only we will never run production on that OS (yes Travis does offer OS X VMs) so I would say it does not really matter.
I would propose the following: I will put clang 3.7 & 3.8 for Linux and keep XCode 7.2 for OS X (last version is 7.3). But officially we only support 3.8, if in the future something goes wrong for 3.7 we will drop the CI for it.
If that sound good to you I will setup 3.8, test and send another request.

**Comment by paboyle** [comment]
Agreed. Please submit.

**Pull request merged**
