### PR TITLE
Update baryon 2pt and add 3pt function

### PR DESCRIPTION
**Pull request by rrhodgson**
Updated the existing baryon 2pt function code in BaryonUtils.h. This allows for the correct treatment of momentum in the initial and final states.
Note the new version is not backwards compatible with the previous version.

Addition of 3pt function code to BaryonUtils.h.

### CODE REVIEW

**Comment by aportelli** [comment]
Thanks! @guelpers and @felixerben is this good for you?

**Comment by felixerben** [comment]
This looks generally good to me. If have a couple of suggestions though:
1) Before this gets merged into develop, could you do some whitespace changes, in particular in the baryon_site function. I know my version wasn't great with this, but it is hard to read the code on a quick glance - i.e. indentations within for-loops are inconsistent and there is sometimes more or less whitespace between a fermion field on a site and the brackets to access its components.
2) By replacing quarks_l and quarks_r just by wick_contraction, it is a bit less obvious how to use the code from within grid - I'm sure it's obvious what it does when looking at the hadrons module, but it would be preferable if BaryonUtils.h would be a bit more self-explanatory. Some minimal documentation in form of a comment at the top of the file or just before ContractBaryons (i.e. saying that wick_contraction needs exactly 6 bool values and how to get the correct ones) would help. One way would be to copy the relevant code from the hadrons module into that comment, so that people who want to use it standalone in grid could just copy that bit to their respective file. Another way would be to add another function which computes nothing but produces the correct wick_contraction from quark_l and quark_r.
3) As far as I can see, ContractBaryons and ContractBaryonsSliced work fundamentally different now, in term of that the former takes a set of wick_contractions as an argument whereas the latter just works for an individual wick_contraction. If this is needed for functionality, again, that's fine, but explain it in a comment so that people who want to use the code know how to do that.

**Comment by rrhodgson** [comment]
@felixerben Thanks for the suggestions

1. Yes I see now that the whitespace is a mess. I'll change my tabs to spaces appropriately.

2. I'll add some documentation in comments to explain how to use the functions.  The ContractBaryons could in theory still take quark_l and quark_r as before, but ContractBaryonsSliced cannot because it must do each contraction separately. Therefore I opted to remove that from both of them. Let me know if you would prefer quark_l and quark_r in ContractBaryons.

3. I could make the usage of ContractBaryons and ContractBaryonsSliced consistent where they both take a single integer wick contraction, but then ContractBaryons will likely become less efficient as it would have to loop over the lattice and 6 colours for ever contraction.

**Comment by felixerben** [comment]
Okay, that makes sense about ContractBaryonsSliced. I think as long as it's documented properly any solution is fine. Just for somebody who is reading the code for the first time, wick_contraction is a bit more of an arbitrary input parameter compared to quarks_l and quarks_r, so it should be made clear what it is supposed to represent.

**Comment by felixerben** [comment]
@aportelli and @guelpers if you have a preference either way please comment as well. I'm not too opinionated about how the code looks as long as it is not too opaque for new users who decide to use Grid as standalone without Hadrons.

**Comment by guelpers** [comment]
Thanks @rrhodgson ! This looks good to me, but I do agree with @felixerben , the code should contain a bit more comments for documentation.

**Comment by aportelli** [comment]
@rrhodgson looks like documenting a but more would be good. You can do that in a comment in the code. On the Hadrons side it would be good to add a page on the documentation website, which you could eventually refer too.

**Comment by rrhodgson** [comment]
I have changed all the whitespace to spaces and it looks better but for some reason is still a bit inconsistent.

I also added a function to produce the wick contractions array from the quarks.

I have also figured out a way to let both ContractBaryons and ContractBaryonsSliced take a bool array of wick contractions. This lets the two functions work in the same way. It is more efficient if all the sinks are the same but the user must select only one contraction manually if they are different.

**Comment by felixerben** [comment]
Looks excellent. I assume you have checked that all the old functions still produce the same results. I can't see any obvious problems with the code though and I like the way it works now. The comments are also good and should answer most questions new users might have, and the wick-contraction routine makes the use straightforward while still giving the full range of functionality, including the one you added. I have no objections to merging this code into develop in the current form. Thanks a lot for your hard work!

**Pull request merged**
