### PR TITLE
Gpu/baryons

### PR DESCRIPTION
**Pull request by felixerben**
Baryons code is now compiling and working on GPU. I have tested:

1) The current code in develop and this code give the same result both on GPU and CPU for 2pt and 3pt Baryon correlators (bit identical).

2) On tesseract, this code produces 2pt and 3pt Baryon correlation functions which agree up to double precision when comparing the GPU and CPU results.

3) I have not tested the same for the sigma-to-nucleon code - I don't think there will be issues, but I can do that. Need to ask Raoul for an xml.

Just a comment: There are a lot of whitespace changes. I did this to have the same indentation rule as in A2AUtils.h - beforehand this was not consistent.

### CODE REVIEW

**Review by aportelli — CHANGES_REQUESTED** [review]
Thanks! White space changes sound justified to restore proper indentation to this files, which you are essentially the only one to edit.

- [ ] remove ITT changes
- [ ] why is the commented line in `A2Autils.h`?

**Comment by felixerben** [comment]
ITT changes are removed. 
The commented line in A2AUtils.h gave me a warning for a variable that is unused. I guess this is the worst solution - Any preference about whether I should leave the file un-touched or whether I should just delete the line?

**Comment by felixerben** [comment]
Current state of testing the code:

- In addition to the 2pt and 3pt routines, also the SigmaToNucleon Eye/NonEye routines are checked to produce the same output on CPU (Raoul's old code used in CPU production), CPU (new code), GPU (new code)
- There is an issue with the SigmaToNucleonNonEye routine: at runtime the warning 'Cuda error out of memory'. It's just a warning, and the code terminates, but produces a correlator file filled with zeros.
- Commenting out either line 1340 or line 1342 prevents the warning and makes comparison of the output with the CPU run possible (but output files are half filled with zeros in this case)

I suggest merging this code into develop, then filing an issue in grid and working on that soon. The current state (compiling & running with the exception of 1/4 routines) is preferable to what's in develop (not compiling for GPU, still a bug in there which Raoul has fixed on his local fork).

**Comment by felixerben** [comment]
With tesseract being up again, I was able to test the suggested fix (swap orders of accelerator_for and if statements in the routine that got a Cuda error: out of memory). The program runs fine now and all routines give constistent results on GPU and CPU.

There was a further suggestion by Peter that I might be able to get rid of the 'mobj2' templating, as the  view objects of the SlicedPropagators and Propagators from Hadrons might be the same now - this is not the case, there is still a type difference, one of them being a simd vector as opposed to the other one.

**Comment by felixerben** [comment]
The code isn't profiled for GPU yet, but I suggest we merge this working code and then work on optimising it at a later stage. The code was profiled for CPU some months ago.

**Pull request merged**
