### PR TITLE
Various fixes & updates

### PR DESCRIPTION
**Pull request by aportelli**
##### Fixes:
- `icpc` header fix for OS X
- *re*-fix of the test Make.inc 

##### New:
- Bernoulli RNG
- `FermToProp` and `PropToFerm` functions
- utility function to read `std::vector` from a string (blank separated values, useful for XML parsing)

### CODE REVIEW

**Comment by paboyle** [comment]
/usr/linux-k1om-4.7/linux-k1om/../x86_64-k1om-linux/include/c++/4.7.0/bits/random.h(4662): error: static assertion failed with "template argument not an integral type"
        static_assert(std::is_integral<_IntType>::value,
        ^
In file included from ../../../lib/lattice/Lattice_base.h(336),
                 from ../../../lib/Lattice.h(31),
                 from ../../../lib/Grid.h(74),
                 from ../../../lib/algorithms/approx/MultiShiftFunction.cc(28):
          detected during instantiation of class "std::discrete_distribution<_IntType> [with _IntType=Grid::RealD={double}]" at line 165 of "../../../lib/lattice/Lattice_rng.h"
In file included from ../../../lib/lattice/Lattice_base.h(336),
                 from ../../../lib/Lattice.h(31),
                 from ../../../lib/Grid.h(74),
                 from ../../../lib/algorithms/approx/MultiShiftFunction.cc(28):

My ICPC compile for KNC on Babbage is failing -- seems to assert must have an integer type
param for bernoulli.

**Comment by paboyle** [comment]
I patched the Lattice_rng to use an int32_t in discrete_distribution and rely on "fill" to typecast to real.

**Comment by aportelli** [comment]
Thanks for the patch, the C++11 standard indeed specify that this must be an integral type. I guess clang is somewhat more tolerant on that requirement.
I use this generator to implement Z_2 sources in the measurement code.

**Comment by paboyle** [comment]
suspect it is a function of the libstdc++.

**Pull request merged**
