### PR TITLE
Wilson+Clover multigrid + some more linear solvers

### PR DESCRIPTION
**Pull request by DanielRichtmann**
Hi,

as discussed, here a first version of a multigrid solver for Wilson and WilsonClover. Both converge but are still WIP.

Features:
  * Wilson + WilsonClover MG (atm with 2 levels) currently implemented in test files
  * GMRES, FGMRES, MR solver algorithms + tests for different actions

Tested with:
  * non-MPI builds for AVX and AVX2 targets using clang 5.0.1 and gcc 7.2.1 

TODOs/WIP:
  * Get more levels to work (my current implementation of Mdir & Mdiag in CoarsenedMatrix isn't correct yet -> didn't push that)
  * Refactor into proper algorithm

Review/comments are very welcome.

### CODE REVIEW

**Comment by DanielRichtmann** [comment]
Hi,

with the updates I just pushed, the MG preconditioner now supports n levels (although I limit it to a maximum of 4), passes all of the checks for all levels (see member function runChecks), and shows expected behavior in terms of iteration counts.

I was able to limit the changes to the existing infrastructure to a minimum (i.e., the datatypes in CoarsenedMatrix, Aggregation, and the transfer utils are back to the original ones in develop). There is something I'd like to discuss though:

With HDCR, you do Petrok-Galerkin coarsening (D_c^dag = D_c), whereas Wilson MG uses Galerkin coarsening (D_c^dag = g5 * D_c * g5). Currently, I just commented the original code in CoarsenedMatrix::Mdag but I think that this class should be able to support both types. For instance, one could just make CoarsenedMatrix virtual and derive two subclasses from it. Let me know what you think.

Comments on this as well as general ones / review are very welcome.

**Comment by paboyle** [comment]
I reviewed and merged this. It was MUCH cleaner than I expected, thanks. 
Useful to merge this back to develop BEFORE I merge feature/gpu-port back into develop.
Many thanks for the features !

**Comment by paboyle** [comment]
Will see how the CI goes now this went into develop, and patch anything required.

**Comment by paboyle** [comment]
Agree we need to look at the g5 M g5 vs HDCR. Merged it since we can fix it later on develop.
Since your changes look pretty clean, we should perhaps add you to the developers list and allow you to manipulate directly after conversation & agreement.

**Comment by DanielRichtmann** [comment]
Thanks, glad to hear this.

I've done some more work in the mean time (mainly to speed up the MG setup) that I'd like to get reviewed and merged and also some further ideas that are not implemented yet. I can live with creating further PRs for these changes once they are up on GitHub, but I agree that adding me to the developers list would make things more convenient.

**Pull request merged**
