### PR TITLE
Feature/hadrons

### PR DESCRIPTION
**Pull request by Lanny91**
Conserved current for Wilson & Shamir DWF (conserved sink contraction & sequential insertion), plus tests.

Test summary:
 - Ward Identity checks
 - Consistency check between conserved sink contraction and sequential insertion
 - Correlator test case agrees with UKhadron

Will implement Mobius shortly, but please review what is here so far.

### CODE REVIEW

**Comment by Lanny91** [comment]
OK it seems that all the checks should pass in principle, however the Travis CI build fails for one of the checks (for GCC 4.9) as it gets the error 

> virtual memory exhausted: Cannot allocate memory

during compilation with single precision. Double precision compiles fine. Possibly this is a sign that Grid is starting to grow too big for Travis?

**Comment by aportelli** [comment]
Hi Andrew,
This looks very good. Let us a bit of time to go over your changes and we'll come back to you (probably in one of the call). Don't worry about Travis, the TeamCity server in Edinburgh is the replacement for it, we'll switch off Travis soon.

**Comment by Lanny91** [comment]
Updates to this request:
 - Module to perform sink smearing external to contraction modules
 - Sink smearing compatibility in 3pt contraction modules
 - Conserved current takes 5D vectorisation into account

**Comment by aportelli** [comment]
Hi Andrew,

I just read though all of it and it looks like you did a fantastic job! Thanks. There are things here and there that I would like to change but this is mainly about code organisation so I am happy to take care of it after the merge. But FYI:

- In some of the contraction it is expected that some of the propagators *have* to be sinked beforehand. I would like to think if this can be more flexible.
- A lot of your current related work assume DW type of fermions, especially the 4D<->5D conversion and the AWI test, I will fence it a bit more. For example we can test the Wilson AWI too.
- The Hadrons tests are less and less looking as simple programs somebody can read to learn. I think they should go back as the simple form they had before. But all the work you done here could be transferred to some utility programs somewhere else.

Comments welcome

**Comment by Lanny91** [comment]
Hi Antonin,

Thanks for going through all this. Please feel free to make changes as you think appropriate. I did think a little about the contraction routines requiring pre-sinked propagators being a little inflexible but as a first implementation I think it will suffice for most usage cases.

I don't think I completely understand what you mean about the simple form of the tests, maybe this is a matter of style? I do think though that Hadrons should have some clearly presented examples to get users started - perhaps the tests fulfil this role but it might be better to have an explicit "examples" directory to point users towards.

**Pull request merged**
