### PR TITLE
Messaging and a fix for QPACE3 compilation with Intel 18

### PR DESCRIPTION
**Pull request by lehner**

### CODE REVIEW

**Comment by lehner** [comment]
In addition to the original PR, this now also adds a fix for non-summit GPU memory access in CoarsenedMatrix, see 
b2087f1 .

**Review by paboyle — COMMENTED** [review]
Can you please remove:

Grid/algorithms/CoarsenedMatrix.h
Grid/allocator/MemoryManagerCache.cc

from this request.

I've made the MemorManager independently, plus one other bug fix you will need to pull back. (don't worry the bug self traps and triggers an assert).

The Coarsened matrix I did differently and independently after an audit.

**Comment by paboyle** [comment]
Also, if you had sent these in as separate requests, I could have reviewed them independently and approved them months ago. You coupled a request on multigrid to the other requests, when the multigrid sectors is my daily work, and was both dangerous and subtle. Accumulating many changes cripples the review, as ALL must be approved to accept ANY.
With five files, 0.6*0.6*0.6*0.6*0.6 =8% chance of any being accepted when each file had a 60% chance....

**Review by paboyle — COMMENTED** [review]
p.s. as far as I can tell GitHub doesn't let me select a subset of files to accept.
git-cherry-pick might, but it is a project to learn that. 
Had hoped downloading GitHub Desktop would help, but so far doesn't look like it,
so I have to bounce this back (or accept and then revert which is annoying).

**Comment by paboyle** [comment]
Merged, was better than screwing around.

**Pull request merged**
