### PR TITLE
MSource::jacobi smear + sort file contents of Modules.hpp and modules.inc

### PR DESCRIPTION
**Pull request by nils-asmussen**
1) Add module MSource::JacobiSmear.

2) The script make_module_list.sh recreates the files Modules.hpp and modules.inc. The output is not sorted which leads to large diffs. This unnecessarily increases the git history due to the large diffs and makes it harder to see what has actually changed. Therefore I suggest to use the sort command in make_module_list.sh as implemented in this merge request.

Please feel free to comment on both parts of the merge request. If wished for, I can remove the second part.

### CODE REVIEW

**Comment by aportelli** [comment]
All good to me thanks! Just one modification: please do not call the gauge field `U` in the parameter struct but rather `gauge` to be consistent with other modules.

**Comment by nils-asmussen** [comment]
Thanks, very good point, gauge is a better choice for the name! Changed it.

**Comment by nils-asmussen** [comment]
I am the lucky one to find the last specimen of the dying species of QCD namespace in Grid!

Proof:
1) Hadrons/Modules/MSource/JacobiSmear.hpp:94:5: error: no template named 'CovariantSmearing'; did you mean 'QCD::CovariantSmearing'?

2) grep -ri namespace | grep QCD (full output):
GridQCDcore.h:NAMESPACE_CHECK(GridQCDCore);
qcd/QCD.h:NAMESPACE_BEGIN(Grid);
qcd/QCD.h:NAMESPACE_END(Grid);
qcd/utils/CovariantSmearing.h:namespace QCD {
qcd/utils/LinalgUtils.h:// I explicitly need these outside the QCD namespace
qcd/hmc/HMC_GridModules.h:// Note: the space time grid should be out of the QCD namespace
qcd/spin/gamma-gen/gamma-gen.nb:<array>\n\nnamespace Grid {\nnamespace QCD {\n\nclass Gamma {\n  public:\n\
qcd/spin/gamma-gen/gamma-gen.nb:namespace QCD {\>\""}]}], ";", "\[IndentingNewLine]", 
parallelIO/NerscIO.h:NAMESPACE_END(QCD);

(The last one does not count because it only ends a namespace '}' that starts by NAMESPACE_BEGIN(Grid))

Shall I fix it myself, or shall I just wait? (I guess rebasing on an older version would not be useful...)

**Comment by aportelli** [comment]
Hi Nils, could you pull the latest develop into that please?

**Comment by aportelli** [comment]
I will merge that, could you update from `develop` first?

**Comment by aportelli** [comment]
Could you also make it independent from #231?

**Comment by aportelli** [comment]
You do not need that to be dependent on #231 anymore, but I have imported separately your rendering of the module header (it is very useful). So you need to update from `develop` and might discover (minor) conflicts.

**Comment by nils-asmussen** [comment]
Hi Antonin, thank you for merging the QCD fix. I have updated this branch. It should be ready as soon as the build system is happy with it.

**Comment by aportelli** [comment]
Thanks, I will merge when this goes green

**Pull request merged**
