### PR TITLE
Corrected some compilation errors 

### PR DESCRIPTION
**Pull request by coppolachan**
zolotarev.h : there was a upper case/lower case problem with the filename in compilation on a unix machine.

SSE4 compilation works now. Vsplat and conj modified to make cshift test pass.
Other tests look ok, but not tested everything. 

The changes in the code are confined to Grid_vComplexF.h and I added the Grid_vector_types.h to generalize the simd structure as discussed.

### CODE REVIEW

**Comment by paboyle** [comment]
Merged and taken ... will now check performance!

**Comment by paboyle** [comment]
Thanks Guido, I've read through and pulled in the changes.

I've a couple of questions:

I'm still a bit unclear about the status of the Grid_vector_types.h -- 
is it usable as a replacement for vComplexF ?

How do the different intrinsics get dropped in for the different specialisations of the Grid_simd class?

**Comment by paboyle** [comment]
regarding the case on Zolotarev ... there's an interesting one there. It turns out the MacOS
file system is case insensitive which is why it compiled for me... :(

**Comment by paboyle** [comment]
Thanks for the set1_ps(-0.f) -- was unaware of that trick, and I will extended it to all
other targets & vComplexD.

**Comment by coppolachan** [comment]
"I'm still a bit unclear about the status of the Grid_vector_types.h -- 
is it usable as a replacement for vComplexF ?"

No, there is the skeleton now, which is Grid_vector_types.h. I have to write the specializations. They will be one file for every different architecture, decided at compile time, no ifdefs around in the code, just in the makefile. The Grid_vector_types.h will be the common backbone. I already tested the idea, I just have to finish the implementation. By now I commited the file to put it in place. I also tested the performance of the mult and it was ok.

**Pull request merged**
